name: Release
on:
  push:

permissions:
  contents: read

jobs:
  build-wails:
    name: Build wails
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            platform: windows/amd64
            output: keyring-wallet-windows.exe
          - os: macos-latest
            platform: darwin/universal
            # wails bug, mac outputfile name not work
            output: Keyring\ Wallet
          - os: ubuntu-20.04
            platform: linux/amd64
            output: keyring-wallet-linux
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Replace auth key in file for Ubuntu or Windows
        if: ${{ runner.os == 'Linux' || runner.os == 'Windows' }}
        shell: bash
        run: |
          sed -i 's/env:INFURA_API_TOKEN/${{ secrets.INFURA_API_TOKEN }}/g' resources/registry.json
          sed -i 's/env:WALLET_CONNECT_PROJECT_ID/${{ secrets.WALLET_CONNECT_PROJECT_ID }}/g' resources/init.json

      - name: Replace auth key in file for Macos
        if: ${{ runner.os == 'macOS' }}
        shell: bash
        run: |
          sed -i '' 's/env:INFURA_API_TOKEN/${{ secrets.INFURA_API_TOKEN }}/g' resources/registry.json
          sed -i '' 's/env:WALLET_CONNECT_PROJECT_ID/${{ secrets.WALLET_CONNECT_PROJECT_ID }}/g' resources/init.json
      
      - name: cat string
        run: |
          cat resources/init.json
          cat resources/registry.json
      - name: Run tmate
        uses: mxschmitt/action-tmate@v2